default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database:  hotel_booking_development
  
test:
  <<: *default
  database:  hotel_booking_test

production:
  <<: *default
  database:  hotel_booking
  url: <%= ENV['DATABASE_URL'] %>
